### ISSUE TITLE
Add multiple keys/values

### ISSUE THREAD

**Issue by lain-ke** [mateusfreira/nun-db#54]
Hello, is there any way to implement something like this?

![image](https://user-images.githubusercontent.com/59977484/143688508-5183245c-82cf-4ddd-b166-5a7ca912a4cf.png)

**Comment by mateusfreira** [comment]
Hey, @lain-ke thanks for the issue, nun-db only supports single keys record.
You can implement it as a single key concatenating the value for example, 
e.g: 
```js
//Product 1
ProductId: 1,
ProductType: "book Id"
//...
//Product 2
ProductId: 1,
ProductType: "Album Id"
``` 
You can store the key as 1_book_id for product 1 and 1_Album_Id for book. 

You still support multiple keys with a single id.


Let me know if that makes sense. If you can show what you are planing to do I can suggest a way to implement it in nun-db
