### ISSUE TITLE
data file is never written to disk even after 10 minutes

### ISSUE THREAD

**Issue by thienpow** [mateusfreira/nun-db#60]
<img width="1109" alt="Screenshot 2022-02-05 at 6 30 39 PM" src="https://user-images.githubusercontent.com/9796623/152638467-780316a3-49d9-4465-a800-ad20d15df822.png">

if do "docker-compose restart", the db will be gone. will need to create-db again.

and from the test below... seems like queue_len can never be greater than 0 even if i added/updated a record to the todos db
<img width="1326" alt="Screenshot 2022-02-05 at 8 21 42 PM" src="https://user-images.githubusercontent.com/9796623/152641955-4736493f-8e03-4f53-b60b-e6d736edca23.png">

seems like to_snapshot would never be updated/assigned any value from nowhere... there's no code to update it... 
<img width="469" alt="Screenshot 2022-02-05 at 8 53 45 PM" src="https://user-images.githubusercontent.com/9796623/152643031-b7bfcd44-cf6e-4dca-84da-a48e21a73d27.png">

**Comment by mateusfreira** [comment]
@thienpow  but by default, it won't store data on disk,  you need to send a snapshot command.

e.g:
```
nun-db --user $NUN_USER  -p $NUN_PWD --host "https://http.nundb.org" exec "use-db $DB_NAME $DB_TOKEN; snapshot"
```
The default behavior is to only hold data on memory.

In this post I also show how to do it for all databases 
https://mateusfreira.github.io/@mateusfreira-nundb-how-to-backups-all-databases-with-one-command/

**Comment by thienpow** [comment]
maybe can make env config

SNAPSHOT_AUTO=true
SNAPSHOT_INTERVAL=180  # seconds
SNAPSHOT_PATH=/nundb/db

same to the log.. can have something like
LOG_LEVEL=1  # (6=TRACE, 5=DEBUG, 4=INFO, 3=WARN, 2=ERROR, 1=FATAL)
LOG_FILE=filename.log # (if not specified, then the log won't written to file)
LOG_PATH=/nundb/log 
best is if we can make it log as per day/week per file. instead of 1 big file forever.
something like this
https://crates.io/crates/tracing-appender

**Comment by mateusfreira** [comment]
@thienpow  that would be great improvement fell free to push a MR
